# Project-wide Gradle settings.
# IDE (e.g. Android Studio) users:
# Gradle settings configured through the IDE are ignored when building from the command line, check
# build.gradle files instead.
# For more details on how to configure your build environment visit
# http://www.gradle.org/guide/building-gradle
# Tells Gradle to use new Gradle Native Build System
# android.useNewApkCreator=true
# Enables namespacing of each library's R class so that its R class includes only the
# resources declared in the library itself and sees the resources from the libraries it depends on
# This property enables lint to parse partially incorrect XML AndroidManifest files.
# It is very useful for checking so that appcompat and support library version are in the file.
# Since com.android.support:appcompat-v7 23.4.0, this is the default value for minSdkVersion
# android.lintOptions.missingDimensionStrategy += library instead of fail
# android.lintOptions.abortOnError=false
# When set to true, a library module may depend on using AGP APIs from the tools Gradle plugin.
# android.useAndroidX=true
# Kotlin code style for this project: "official" or "obsolete":
kotlin.code.style=official
android.useAndroidX=true
android.nonTransitiveRClass=true
